export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DATE = 'GET_DATE';
export const DETAILS = 'DETAILS';
export const ERROR_REQUEST = 'ERROR_REQUEST';
